
name: 'Github_Actions'

on:
  push:
    branches:
      - 'main'
      - '*'
    paths:
      - 'dev/**'
  pull_request:
    

concurrency: ${{ github.repository }}

jobs:
  dev_cicd:
    name: 'CICD Job dev'
    runs-on: 'ubuntu-latest'

    steps:

      - name: GIT Checkout
        id: 'git-checkout'
        uses: "actions/checkout@v4"

      - name: Terraform Init
        id: 'tf-init'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}
        run: |
          cd ./dev/Org_Templates/terraform-google-cloud-apis
          terraform init
          pwd

      - name: Terraform Plan
        id: 'tf-plan'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}
        run: |
          cd ./dev/Org_Templates/terraform-google-cloud-apis
          terraform plan


      - name: Terraform Apply
        id: 'tf-apply'
        if: |
          github.ref == 'refs/heads/main'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}
        run: |
          cd ./dev/Org_Templates/terraform-google-cloud-apis
          terraform apply --auto-approve

      - name: Terraform Destroy
        id: 'tf-destroy'
        if: |
          github.ref == 'refs/heads/main'
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}
        run: |
          cd ./dev/Org_Templates/terraform-google-cloud-apis
          terraform destroy --auto-approve
    
